#ifndef SECURE_ELEMENT_H_
#define SECURE_ELEMENT_H_

#define SLOT_LEN 32

#define SALT_SLOT 45
#define SALT_SLOT_LEN SLOT_LEN
#define PASSWD_HASH_SLOT 46
#define PASSWD_HASH_SLOT_LEN SLOT_LEN

#define SE_I2C_BUS_ID 1
#define SHA256_OUTPUT_LEN 32
#define SHA256_INPUT_LEN 48
#define DEFAULT_PASSWD_LEN 11
#define DEFAULT_PASSWD "Nimhs-123s@"
#define MAX_USER_NAME_LEN 1024

#endif /* SECURE_ELEMENT_H_ */
